apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-log-ml-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-log-ml-service
  template:
    metadata:
      labels:
        app: demo-log-ml-service
    spec:
      serviceAccountName: telemetry-access  # Existing SA with Cloud Trace permissions
      containers:
      - name: fastapi-container
        image: us-central1-docker.pkg.dev/durable-unity-468703-a2/my-repo/demo_log:latest
        ports:
        - containerPort: 8200
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/sa-key.json
        volumeMounts:
        - name: sa-key
          mountPath: /secrets
          readOnly: true
        readinessProbe:
          httpGet:
            path: /ready_check
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live_check
            port: 8200
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: sa-key
        secret:
          secretName: gcp-sa-key  # Kubernetes secret containing your SA JSON
