apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      serviceAccountName: telemetry-access
      containers:
      - name: mlflow
        image: python:3.11-slim
        command: ["mlflow", "server",
                  "--backend-store-uri", "sqlite:///mlflow.db",
                  "--default-artifact-root", "gs://mlops-bucket-chaitanya",
                  "--host", "0.0.0.0",
                  "--port", "5000"]
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
